// @flow
import { c3Label, getC3Language } from './C3Language';
// c3: Construct 3's behaviour list, 1:1 (see CLAUDE.md "Behaviour parity").
// Each tile is a GDevelop behaviour plus the settings applied when it is
// added; several tiles may share one GDevelop type (Solid and Jump-thru are
// both the Platform behaviour). Labels are Construct's own, so they bypass
// the terminology rewrite. `icon` is the slug in C3-Icons/behaviour_icons.

export type C3Behavior = {|
  id: string,
  name: {| en: string, pt_BR: string |},
  category: {| en: string, pt_BR: string |},
  type: string,
  defaultName: {| en: string, pt_BR: string |}, // identifier, per language
  presets: { [string]: string },
  icon: string,
  // Events-based extension bundled with the editor (Utils/C3Extensions),
  // installed into the project when the tile is chosen.
  bundledExtension?: string,
|};

const attributes = { en: 'Attributes', pt_BR: 'Atributos' };
const general = { en: 'General', pt_BR: 'Geral' };
const movements = { en: 'Movements', pt_BR: 'Movimentos' };
const threeD = { en: '3D', pt_BR: '3D' };

// Construct's order in the add-behaviour dialog.
export const C3_BEHAVIOR_CATEGORIES = [threeD, attributes, general, movements];

export const C3_BEHAVIORS: Array<C3Behavior> = [
  {
    id: 'solid',
    name: { en: 'Solid', pt_BR: 'Sólido' },
    category: attributes,
    type: 'PlatformBehavior::PlatformBehavior',
    defaultName: { en: 'Solid', pt_BR: 'Solido' },
    presets: { PlatformType: 'NormalPlatform' },
    icon: 'solido',
  },
  {
    id: 'jump-thru',
    name: { en: 'Jump-thru', pt_BR: 'Pular através' },
    category: attributes,
    type: 'PlatformBehavior::PlatformBehavior',
    defaultName: { en: 'JumpThru', pt_BR: 'PularAtraves' },
    presets: { PlatformType: 'Jumpthru' },
    icon: 'pular-atraves',
  },
  {
    id: 'shadow-caster',
    name: { en: 'Shadow caster', pt_BR: 'Projetor de sombra' },
    category: attributes,
    type: 'Lighting::LightObstacleBehavior',
    defaultName: { en: 'ShadowCaster', pt_BR: 'ProjetorDeSombra' },
    presets: {},
    icon: 'projetor-de-sombra',
  },
  {
    id: 'drag-drop',
    name: { en: 'Drag & Drop', pt_BR: 'Arrastar & Soltar' },
    category: general,
    type: 'DraggableBehavior::Draggable',
    defaultName: { en: 'DragDrop', pt_BR: 'ArrastarESoltar' },
    presets: {},
    icon: 'arrastar-e-soltar',
  },
  {
    id: 'anchor',
    name: { en: 'Anchor', pt_BR: 'Âncora' },
    category: general,
    type: 'AnchorBehavior::AnchorBehavior',
    defaultName: { en: 'Anchor', pt_BR: 'Ancora' },
    presets: {},
    icon: 'ancora',
  },
  {
    id: 'destroy-outside',
    name: { en: 'Destroy outside layout', pt_BR: 'Destruir externamente' },
    category: general,
    type: 'DestroyOutsideBehavior::DestroyOutside',
    defaultName: { en: 'DestroyOutside', pt_BR: 'DestruirExternamente' },
    presets: {},
    icon: 'destruir-externamente',
  },
  {
    id: 'tween',
    name: { en: 'Tween', pt_BR: 'Interpolação' },
    category: general,
    type: 'Tween::TweenBehavior',
    defaultName: { en: 'Tween', pt_BR: 'Interpolacao' },
    presets: {},
    icon: 'interpolacao',
  },
  {
    id: 'platform',
    name: { en: 'Platform', pt_BR: 'Plataforma' },
    category: movements,
    type: 'PlatformBehavior::PlatformerObjectBehavior',
    defaultName: { en: 'Platform', pt_BR: 'Plataforma' },
    presets: {},
    icon: 'plataforma',
  },
  {
    id: '8-direction',
    name: { en: '8 Direction', pt_BR: '8 Direções' },
    category: movements,
    type: 'TopDownMovementBehavior::TopDownMovementBehavior',
    defaultName: { en: 'EightDirection', pt_BR: 'OitoDirecoes' },
    presets: { AllowDiagonals: 'true' },
    icon: '8-direcoes',
  },
  {
    id: 'physics',
    name: { en: 'Physics', pt_BR: 'Física' },
    category: movements,
    type: 'Physics2::Physics2Behavior',
    defaultName: { en: 'Physics', pt_BR: 'Fisica' },
    presets: {},
    icon: 'fisica',
  },
  {
    id: 'car',
    name: { en: 'Car', pt_BR: 'Carro' },
    category: movements,
    type: 'Physics3D::PhysicsCar3D',
    defaultName: { en: 'Car', pt_BR: 'Carro' },
    presets: {},
    icon: 'carro',
  },
  {
    id: 'pathfinding',
    name: { en: 'Pathfinding', pt_BR: 'Explorador de rotas' },
    category: movements,
    type: 'PathfindingBehavior::PathfindingBehavior',
    defaultName: { en: 'Pathfinding', pt_BR: 'ExploradorDeRotas' },
    presets: {},
    icon: 'explorador-de-rotas',
  },
  {
    id: 'billboard',
    name: { en: 'Billboard', pt_BR: 'Billboard' },
    category: threeD,
    type: 'Scene3D::Base3DBehavior',
    defaultName: { en: 'Billboard', pt_BR: 'Billboard' },
    presets: {},
    icon: 'billboard',
  },
  {
    id: 'persist',
    name: { en: 'Persist', pt_BR: 'Persistir' },
    category: attributes,
    type: 'SaveState::SaveConfiguration',
    defaultName: { en: 'Persist', pt_BR: 'Persistir' },
    presets: { defaultProfilePersistence: 'Persisted' },
    icon: 'persistir',
  },
  {
    id: 'no-save',
    name: { en: 'No save', pt_BR: 'Não salvar' },
    category: attributes,
    type: 'SaveState::SaveConfiguration',
    defaultName: { en: 'NoSave', pt_BR: 'NaoSalvar' },
    presets: { defaultProfilePersistence: 'DoNotSave' },
    icon: 'nao-salvar',
  },
  // Community extensions (installed on demand from the extension store).
  {
    id: 'bullet',
    name: { en: 'Bullet', pt_BR: 'Projétil' },
    category: movements,
    type: 'AdvancedProjectile::AdvancedProjectile',
    defaultName: { en: 'Bullet', pt_BR: 'Projetil' },
    presets: {},
    icon: 'projetil',
  },
  {
    id: 'orbit',
    name: { en: 'Orbit', pt_BR: 'Órbita' },
    category: movements,
    type: 'EllipseMovement::EllipseMovement',
    defaultName: { en: 'Orbit', pt_BR: 'Orbita' },
    presets: {},
    icon: 'orbita',
  },
  {
    id: 'turret',
    name: { en: 'Turret', pt_BR: 'Canhão' },
    category: movements,
    type: 'Turret::Turret',
    defaultName: { en: 'Turret', pt_BR: 'Canhao' },
    presets: {},
    icon: 'canhao',
  },
  {
    id: 'flash',
    name: { en: 'Flash', pt_BR: 'Piscar' },
    category: general,
    type: 'Flash::Flash',
    defaultName: { en: 'Flash', pt_BR: 'Piscar' },
    presets: {},
    icon: 'piscar',
  },
  {
    id: 'pin',
    name: { en: 'Pin', pt_BR: 'Fixar' },
    category: general,
    type: 'Sticker::Sticker',
    defaultName: { en: 'Pin', pt_BR: 'Fixar' },
    presets: {},
    icon: 'fixar',
  },
  {
    id: 'wrap',
    name: { en: 'Wrap', pt_BR: 'Dar a volta' },
    category: general,
    type: 'ScreenWrap::ScreenWrap',
    defaultName: { en: 'Wrap', pt_BR: 'DarAVolta' },
    presets: {},
    icon: 'dar-a-volta',
  },
  {
    id: 'bound-to-layout',
    name: { en: 'Bound to layout', pt_BR: 'Restrito ao layout' },
    category: general,
    type: 'StayOnScreen::StayOnScreen',
    defaultName: { en: 'BoundToLayout', pt_BR: 'RestritoAoLayout' },
    presets: {},
    icon: 'restrito-ao-layout',
  },
  {
    id: 'scroll-to',
    name: { en: 'Scroll To', pt_BR: 'Centrar em' },
    category: general,
    type: 'SmoothCamera::SmoothCamera',
    defaultName: { en: 'ScrollTo', pt_BR: 'CentrarEm' },
    presets: {},
    icon: 'centrar-em',
  },
  // Our own events-based extensions (nothing close enough in GDevelop or the
  // reviewed store), see Utils/C3Extensions.
  {
    id: 'sine',
    name: { en: 'Sine', pt_BR: 'Senóide' },
    category: movements,
    type: 'A3Sine::Sine',
    defaultName: { en: 'Sine', pt_BR: 'Senoide' },
    presets: {},
    icon: 'senoide',
    bundledExtension: 'A3Sine',
  },
  {
    id: 'rotate',
    name: { en: 'Rotate', pt_BR: 'Girar' },
    category: movements,
    type: 'A3Rotate::Rotate',
    defaultName: { en: 'Rotate', pt_BR: 'Girar' },
    presets: {},
    icon: 'girar',
    bundledExtension: 'A3Rotate',
  },
  {
    id: 'move-to',
    name: { en: 'MoveTo', pt_BR: 'Mover para' },
    category: movements,
    type: 'A3MoveTo::MoveTo',
    defaultName: { en: 'MoveTo', pt_BR: 'MoverPara' },
    presets: {},
    icon: 'mover-para',
    bundledExtension: 'A3MoveTo',
  },
  {
    id: 'follow',
    name: { en: 'Follow', pt_BR: 'Seguir' },
    category: movements,
    type: 'A3Follow::Follow',
    defaultName: { en: 'Follow', pt_BR: 'Seguir' },
    presets: {},
    icon: 'seguir',
    bundledExtension: 'A3Follow',
  },
  {
    id: 'tile-movement',
    name: { en: 'Tile movement', pt_BR: 'Movimento em grid' },
    category: movements,
    type: 'A3TileMovement::TileMovement',
    defaultName: { en: 'TileMovement', pt_BR: 'MovimentoEmGrid' },
    presets: {},
    icon: 'movimento-em-grid',
    bundledExtension: 'A3TileMovement',
  },
  {
    id: 'custom',
    name: { en: 'Custom', pt_BR: 'Personalizado' },
    category: movements,
    type: 'A3CustomMovement::CustomMovement',
    defaultName: { en: 'Custom', pt_BR: 'Personalizado' },
    presets: {},
    icon: 'personalizado',
    bundledExtension: 'A3CustomMovement',
  },
  {
    id: 'fade',
    name: { en: 'Fade', pt_BR: 'Esmaecer' },
    category: general,
    type: 'A3Fade::Fade',
    defaultName: { en: 'Fade', pt_BR: 'Esmaecer' },
    presets: {},
    icon: 'esmaecer',
    bundledExtension: 'A3Fade',
  },
  {
    id: 'timer',
    name: { en: 'Timer', pt_BR: 'Cronômetro' },
    category: general,
    type: 'A3Timer::Timer',
    defaultName: { en: 'Timer', pt_BR: 'Cronometro' },
    presets: {},
    icon: 'cronometro',
    bundledExtension: 'A3Timer',
  },
  {
    id: 'line-of-sight',
    name: { en: 'Line of sight', pt_BR: 'Campo de visão' },
    category: general,
    type: 'A3LineOfSight::LineOfSight',
    defaultName: { en: 'LineOfSight', pt_BR: 'CampoDeVisao' },
    presets: {},
    icon: 'campo-de-visao',
    bundledExtension: 'A3LineOfSight',
  },
];

export const getC3Behavior = (id: ?string): ?C3Behavior =>
  id ? C3_BEHAVIORS.find(behavior => behavior.id === id) : null;

export { c3Label } from './C3Language';

// The behaviour name given on the object, in the UI language.
export const c3DefaultName = (tile: C3Behavior): string =>
  c3Label(tile.defaultName, getC3Language());
